//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartzWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public string AspNetUsersId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string CronExpression { get; set; }
        public System.DateTime NextRunTime { get; set; }
        public Nullable<System.DateTime> PreviousRunTime { get; set; }
        public Nullable<int> RepeatTime { get; set; }
        public bool IsDeleted { get; set; }
        public bool Run_Forever { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Job Job { get; set; }
    }
}
